---
name: Packer build

on:
  push:
    branches:
      - main
    paths:
      - "**.pkr.hcl"
  pull_request:
    branches:
      - main
    paths:
      - "**.pkr.hcl"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  packer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: packer
    
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
          - 32000:5000
          
    env:
      local-repo: localhost:32000/mirc-ctp
      local-tag: ci
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Packer install
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get -q update && sudo apt-get -yq install packer

      - name: Build Artifacts
        run: |
          [[ -f Makefile ]] && make .state_ctp-docker repo=${{ env.local-repo}} tag=${{ env.local-tag }}
          echo "mirc-ctp-build-ver=$(cat latest-build)" >> $GITHUB_ENV
          docker push ${{ env.local-repo}}:${{ env.local-tag }}
        env:
          PACKER_LOG: 1
          
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/mirc-ctp
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha
            type=raw,value=${{ env.mirc-ctp-build-ver }}

      - name: Push docker image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ${{ env.local-repo}}:${{ env.local-tag }}
          dst: |
            ${{ steps.meta.outputs.tags }}
